language: android
dist: trusty
android:
  components:
    - build-tools-29.0.3
    - android-29

script:
  - ./gradlew clean :silentorder:assembleRelease

deploy:
  skip_cleanup: true
  provider: script
  script: ./gradlew :silentorder:bintrayUpload
  on:
    tags: true
